---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: camel-s3-integration
  namespace: {{ .Values.dataScienceProjectNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: camel-s3-pipeline-runner-dspa
  namespace: {{ .Values.dataScienceProjectNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-runner-dspa
subjects:
- kind: ServiceAccount
  name: camel-s3-integration
