---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: '{{ .Values.cicdApplication.targetRevision }}'
    app.openshift.io/vcs-uri: '{{ .Values.cicdApplication.repoURL }}'
  name: camel-s3-integration
  namespace: '{{ .Values.dataScienceProjectNamespace }}'
  labels:
    app: camel-s3-integration
    app.kubernetes.io/component: camel-s3-integration
    app.kubernetes.io/instance: camel-s3-integration
    app.kubernetes.io/name: camel-s3-integration
    app.kubernetes.io/part-of: camel-integrations
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-17-ubi8
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'camel-s3-integration:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: '{{ .Values.cicdApplication.repoURL }}'
      ref: '{{ .Values.cicdApplication.targetRevision }}'
    contextDir: integrations/camel-s3-integration
  triggers:
    - type: ConfigChange
    - type: Generic
      generic:
        secretReference:
          name: camel-s3-integration-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: camel-s3-integration-github-webhook-secret
  runPolicy: Serial
---
kind: Secret
apiVersion: v1
metadata:
  name: camel-s3-integration-generic-webhook-secret
  namespace: '{{ .Values.dataScienceProjectNamespace }}'
  labels:
    app: camel-s3-integration
    app.kubernetes.io/component: camel-s3-integration
    app.kubernetes.io/instance: camel-s3-integration
    app.kubernetes.io/name: camel-s3-integration
    app.kubernetes.io/part-of: camel-integrations
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-17-ubi8
stringData:
  WebHookSecretKey: {{ .Values.genericWebhookSecretKey }}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: camel-s3-integration-github-webhook-secret
  namespace: '{{ .Values.dataScienceProjectNamespace }}'
  labels:
    app: camel-s3-integration
    app.kubernetes.io/component: camel-s3-integration
    app.kubernetes.io/instance: camel-s3-integration
    app.kubernetes.io/name: camel-s3-integration
    app.kubernetes.io/part-of: camel-integrations
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-17-ubi8
stringData:
  WebHookSecretKey: {{ .Values.githubWebhookSecretKey }}
type: Opaque
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: '{{ .Values.cicdApplication.targetRevision }}'
    app.openshift.io/vcs-uri: '{{ .Values.cicdApplication.repoURL }}'
  name: camel-s3-integration
  namespace: '{{ .Values.dataScienceProjectNamespace }}'
  labels:
    app: camel-s3-integration
    app.kubernetes.io/component: camel-s3-integration
    app.kubernetes.io/instance: camel-s3-integration
    app.kubernetes.io/name: camel-s3-integration
    app.kubernetes.io/part-of: camel-integrations
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-17-ubi8
spec:
  lookupPolicy:
    local: false
