kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
    app.openshift.io/vcs-ref: '{{ .Values.cicdApplication.targetRevision }}'
    app.openshift.io/vcs-uri: '{{ .Values.cicdApplication.repoURL }}'
  name: camel-s3-integration
  namespace: {{ .Values.dataScienceProjectNamespace }}
  labels:
    app: camel-s3-integration
    app.kubernetes.io/component: camel-s3-integration
    app.kubernetes.io/instance: camel-s3-integration
    app.kubernetes.io/name: camel-s3-integration
    app.kubernetes.io/part-of: camel-integrations
    app.openshift.io/runtime: quarkus
    app.openshift.io/runtime-version: openjdk-17-ubi8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camel-s3-integration
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: camel-s3-integration
        deployment: camel-s3-integration
    spec:
      containers:
        - name: camel-s3-integration
          image: >-
            image-registry.openshift-image-registry.svc:5000/{{ .Values.dataScienceProjectNamespace }}/camel-s3-integration:latest
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          envFrom:
            - secretRef:
                name: camel-s3-integration-creds
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
