---

apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Values.dataScienceProjectNamespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Set sync-wave to -1 to avoid conflicts with other resources
    openshift.io/description: "{{ .Values.dataScienceProjectDisplayName }}"
    openshift.io/display-name: '{{ .Values.dataScienceProjectDisplayName }}'
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops #argocd instance ns
    kubernetes.io/metadata.name: "{{ .Values.dataScienceProjectNamespace }}"
    modelmesh-enabled: 'false'
    opendatahub.io/dashboard: 'true'