apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  annotations:
    tekton.dev/displayName: Upload a Pipeline to a KFP cluster
    tekton.dev/pipelines.minVersion: '0.19'
    tekton.dev/tags: 'kfp'

  name: kfp-upload

  labels:
    app.kubernetes.io/version: '0.1'
    operator.tekton.dev/provider-type: redhat
spec:
  description: >-
    These Task will compile and upload a Pipeline to a KFP cluster
  params:
    - description: The image used where python is installed
      name: TASK_IMAGE
      type: string
      default: quay.io/modh/runtime-images:runtime-cuda-tensorflow-ubi9-python-3.9-2023b-20240301
    - description: The pipeline python script to compile
      name: PIPELINE_NAME
      type: string
      default: deploy
    - description: The requiretments file to install
      name: REQUIREMENTS_FILE
      type: string
      default: requirements.txt
    - description: The path to the pipeline python script
      name: PIPELINES_PATH
      type: string
      default: pipeline
  results:
    - description: The Pipeline Id of the kfp pipeline uploaded
      name: PIPELINE_ID
  steps:
    - image: $(params.TASK_IMAGE)
      name: compile
      resources: {}
      workingDir: $(workspaces.source.path)
      env:
        - name: PIPELINE_NAME
          value: $(params.PIPELINE_NAME)
        - name: PIPELINES_PATH
          value: $(params.PIPELINES_PATH)
      script: |
        #!/bin/sh

        echo "Compiling pipeline $(params.PIPELINE_NAME).yaml"

        echo "Current directory"
        pwd

        echo "List files"
        ls -lstrh

        cd $(params.PIPELINES_PATH)

        pip install -r $(params.REQUIREMENTS_FILE)

        python $(params.PIPELINE_NAME).py

        echo "PATH TO $(params.PIPELINE_NAME).yaml"
        ls -lstrh $(params.PIPELINE_NAME).yaml
    - image: $(params.TASK_IMAGE)
      name: upload
      resources: {}
      workingDir: $(workspaces.source.path)
      env:
        - name: PIPELINE_NAME
          value: $(params.PIPELINE_NAME)
        - name: PIPELINES_PATH
          value: $(params.PIPELINES_PATH)
      script: |
        #!/bin/sh

        echo "Uploading pipeline $(params.PIPELINE_NAME).yaml"

        echo "Current directory"
        pwd

        echo "List files"
        ls -lstrh

        echo "Change directory to $(params.PIPELINES_PATH)"
        cd $(params.PIPELINES_PATH)

        echo "PATH TO $(params.PIPELINE_NAME).yaml"
        ls -lstrh $(params.PIPELINE_NAME).yaml

        # Upload the pipeline
        export NAMESPACE_NAME="$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)"
        export AUTH_HEADER="Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"
        export PIPELINE_NAME="$(params.PIPELINE_NAME)"

        echo "NAMESPACE_NAME: $NAMESPACE_NAME PIPELINE_NAME: $PIPELINE_NAME AUTH_HEADER: $AUTH_HEADER"

        export SVC_HOST=ds-pipeline-dspa:8080
        export SVC="http://${SVC_HOST}"

        # Check if the pipeline already exists
        echo "Checking if the pipeline already exists using ${SVC}/apis/v2beta1/pipelines/${PIPELINE_NAME}"
        curl -X GET \
          -H "Authorization: ${AUTH_HEADER}" \
          ${SVC}/apis/v2beta1/pipelines/${PIPELINE_NAME} | grep -q "not found"

        if [ $? -eq 1 ]; then
          echo ">>> Pipeline already exists"
          # If the pipeline does not exist, upload it
          curl -X POST \
            -H "Authorization: ${AUTH_HEADER}" \
            -F "uploadfile=@./$(params.PIPELINE_NAME).yaml" \
            ${SVC}/apis/v2beta1/pipelines/upload
        else
          echo ">>> Pipeline does not exist"
          # If the pipeline already exists, upload a new version
          curl -X POST \
            -H "Authorization: ${AUTH_HEADER}" \
            -F "uploadfile=@./$(params.PIPELINE_NAME).yaml" \
            ${SVC}/apis/v2beta1/pipelines/upload_version
        fi
  workspaces:
    - mountPath: /workspace/source
      name: source
