apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  annotations:
    tekton.dev/displayName: Upload a Pipeline to a KFP cluster
    tekton.dev/pipelines.minVersion: '0.19'
    tekton.dev/tags: 'kfp'

  name: kfp-upload

  labels:
    app.kubernetes.io/version: '0.1'
    operator.tekton.dev/provider-type: redhat
spec:
  description: >-
    These Task will compile and upload a Pipeline to a KFP cluster
  params:
    - description: The image used where python is installed
      name: TASK_IMAGE
      type: string
      default: quay.io/modh/runtime-images:runtime-cuda-tensorflow-ubi9-python-3.9-2023b-20240301
    - description: The pipeline python script to compile
      name: PIPELINE_NAME
      type: string
      default: deploy
    - description: The requiretments file to install
      name: REQUIREMENTS_FILE
      type: string
      default: requirements.txt
    - description: The path to the pipeline python script
      name: PIPELINES_PATH
      type: string
      default: pipeline
  results:
    - description: The Pipeline Id of the kfp pipeline uploaded
      name: PIPELINE_ID
  steps:
    - image: $(params.TASK_IMAGE)
      name: compile
      resources: {}
      workingDir: $(workspaces.source.path)
      env:
        - name: PIPELINE_NAME
          value: $(params.PIPELINE_NAME)
        - name: PIPELINES_PATH
          value: $(params.PIPELINES_PATH)
      script: |
        #!/bin/sh

        pwd

        ls -lstrh

        cd $(PIPELINES_PATH)

        pip install -r $(params.REQUIREMENTS_FILE)

        python $(params.PIPELINE_NAME).py

        echo "PATH TO $(params.PIPELINE_NAME).yaml"
        ls -lstrh $(params.PIPELINE_NAME).yaml
  workspaces:
    - mountPath: /workspace/source
      name: source
