apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: "{{{ .Values.instanceName }}"
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: "{{ .Values.modelDeploymentUploadTektonPipelineName }}-github-listener"
  name: el-{{ .Values.modelDeploymentUploadTektonPipelineName }}-github-listener
  namespace: {{ .Values.dataScienceProjectNamespace }}
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-{{ .Values.modelDeploymentUploadTektonPipelineName }}-github-listener
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: "{{{ .Values.instanceName }}"
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: "{{ .Values.modelDeploymentUploadTektonPipelineName }}-gitea-listener"
  name: el-{{ .Values.modelDeploymentUploadTektonPipelineName }}-gitea-listener
  namespace: {{ .Values.dataScienceProjectNamespace }}
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-{{ .Values.modelDeploymentUploadTektonPipelineName }}-gitea-listener
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: "{{{ .Values.instanceName }}"
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: "{{ .Values.modelDeploymentUploadTektonPipelineName }}-gitlab-listener"
  name: el-{{ .Values.modelDeploymentUploadTektonPipelineName }}-gitlab-listener
  namespace: {{ .Values.dataScienceProjectNamespace }}
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-{{ .Values.modelDeploymentUploadTektonPipelineName }}-gitlab-listener
    weight: 100
  wildcardPolicy: None