apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: "{{ .Values.instanceName }}"
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: "{{ .Values.modelDeploymentUploadTektonPipelineName }}-github"
  name: el-{{ .Values.modelDeploymentUploadTektonPipelineName }}-github
  namespace: {{ .Values.dataScienceProjectNamespace }}
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-{{ .Values.modelDeploymentUploadTektonPipelineName }}-github
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: "{{ .Values.instanceName }}"
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: "{{ .Values.modelDeploymentUploadTektonPipelineName }}-gitea"
  name: el-{{ .Values.modelDeploymentUploadTektonPipelineName }}-gitea
  namespace: {{ .Values.dataScienceProjectNamespace }}
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-{{ .Values.modelDeploymentUploadTektonPipelineName }}-gitea
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: "{{ .Values.instanceName }}"
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: "{{ .Values.modelDeploymentUploadTektonPipelineName }}-gitlab"
  name: el-{{ .Values.modelDeploymentUploadTektonPipelineName }}-gitlab
  namespace: {{ .Values.dataScienceProjectNamespace }}
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-{{ .Values.modelDeploymentUploadTektonPipelineName }}-gitlab
    weight: 100
  wildcardPolicy: None