modelApplication:
  repoURL: https://github.com/alpha-hack-program/sagemaker-rhoai.git
  path: gitops/model
  targetRevision: main

dataScienceProjectDisplayName: fraud-detection
dataScienceProjectNamespace: fraud-detection

instanceName: fraud-detection

model:
  name: fraud-detection
  displayName: Fraud Detection
  maxReplicas: 1
  format: onnx
  apiProtocol: REST
  staging:
    connection:
      name: model-staging
      displayName: Model Staging
      type: s3
      scheme: http
      awsAccessKeyId: minio
      awsSecretAccessKey: minio123
      awsDefaultRegion: none
      awsS3Bucket: staging
      awsS3Endpoint: minio.ic-shared-minio.svc:9000
  runtime:
    name: fraud-detection-model-server
    displayName: Fraud Detection Model Server
    image: quay.io/modh/openvino_model_server@sha256:6c7795279f9075bebfcd9aecbb4a4ce4177eec41fb3f3e1f1079ce6309b7ae45
    resources:
      limits:
        cpu: '2'
        memory: 8Gi
      requests:
        cpu: '1'
        memory: 4Gi
    connection:
      name: model-runtime
      displayName: Model Runtime
      type: s3
      scheme: http
      awsAccessKeyId: minio
      awsSecretAccessKey: minio123
      awsDefaultRegion: none
      awsS3Bucket: models
      awsS3Endpoint: minio.ic-shared-minio.svc:9000
  volumes:
    shm:
      sizeLimit: 2Gi
    
modelConnection:
  name: llm
  displayName: llm
  type: s3
  scheme: http
  awsAccessKeyId: minio
  awsSecretAccessKey: minio123
  awsDefaultRegion: none
  awsS3Bucket: models
  awsS3Endpoint: minio.ic-shared-minio.svc:9000

documentsConnection:
  name: documents
  displayName: documents
  type: s3
  scheme: http
  awsAccessKeyId: minio
  awsSecretAccessKey: minio123
  awsDefaultRegion: none
  awsS3Bucket: documents
  awsS3Endpoint: minio.ic-shared-minio.svc:9000

pipelinesConnection:
  name: pipelines
  displayName: pipelines
  type: s3
  scheme: http
  awsAccessKeyId: minio
  awsSecretAccessKey: minio123
  awsDefaultRegion: none
  awsS3Bucket: pipelines
  awsS3Endpoint: minio.ic-shared-minio.svc:9000

minio:
  name: minio
  namespace: ic-shared-minio

documentsMilvusConnection:
  name: documents
  collectionName: documents

milvus:
  name: milvus
  namespace: ic-shared-milvus
  username: root
  password: Milvus
  port: '19530'
  host: vectordb-milvus

setup:
  image: quay.io/atarazana/hf-cli:latest