vcs:
  uri: https://github.com/alpha-hack-program/sagemaker-rhoai.git
  ref: main

gitSslVerify: true
modelDeploymentUploadTektonPipelineName: fraud-detection-kfp-upload
sourceWorkspaceSize: 2Gi

cicdApplication:
  repoURL: https://github.com/alpha-hack-program/sagemaker-rhoai.git
  path: gitops/fraud-detection-cicd
  targetRevision: main

genericWebhookSecretKey: 'ABCDEFGHIJKL'
githubWebhookSecretKey: 'ABCDEFGHIJKL'

dataScienceProjectDisplayName: fraud-detection
dataScienceProjectNamespace: fraud-detection

instanceName: fraud-detection

model:
  name: fraud-detection
  displayName: Fraud Detection
  maxReplicas: 1
  format: onnx
  apiProtocol: REST
  staging:
    connection:
      name: model-staging
      displayName: Model Staging
      type: s3
      scheme: http
      awsAccessKeyId: minio
      awsSecretAccessKey: minio123
      awsDefaultRegion: none
      awsS3Bucket: staging
      awsS3Endpoint: minio.ic-shared-minio.svc:9000
  runtime:
    name: fraud-detection-model-server
    displayName: Fraud Detection Model Server
    image: quay.io/modh/openvino_model_server@sha256:6c7795279f9075bebfcd9aecbb4a4ce4177eec41fb3f3e1f1079ce6309b7ae45
    resources:
      limits:
        cpu: '2'
        memory: 8Gi
      requests:
        cpu: '1'
        memory: 4Gi
    connection:
      name: model-runtime
      displayName: Model Runtime
      type: s3
      scheme: http
      awsAccessKeyId: minio
      awsSecretAccessKey: minio123
      awsDefaultRegion: none
      awsS3Bucket: models
      awsS3Endpoint: minio.ic-shared-minio.svc:9000
  volumes:
    shm:
      sizeLimit: 2Gi
    
pipelines:
  connection:
    name: pipelines
    displayName: pipelines
    type: s3
    scheme: http
    awsAccessKeyId: minio
    awsSecretAccessKey: minio123
    awsDefaultRegion: none
    awsS3Bucket: pipelines
    awsS3Endpoint: minio.ic-shared-minio.svc:9000

workbench:
  name: fraud-detection-workbench
  displayName: Fraud Detection Workbench
  image:
    name: tensorflow:2024.1
    displayName: TensorFlow
  resources:
    limits:
      cpu: '2'
      memory: 8Gi
      # nvidiaGpu: '1'
    requests:
      cpu: '1'
      memory: 6Gi
      # nvidiaGpu: '1'

setup:
  image: quay.io/atarazana/hf-cli:latest